language: c

env:
 global:
  - EnableNuGetPackageRestore=true 
  - MONO_VER="3.2.1"
  - MONO_SUBVER="_1"

install:
  - sudo apt-add-repository -y 'deb http://ppa.launchpad.net/directhex/monoxide/ubuntu precise main'
  - sudo apt-get update
  - sudo apt-get -y --force-yes install mono-complete # mono should include everything needed.

script:
 - xbuild /p:TargetFrameworkProfile= ./src/ExplorerShortcutHelper/ExplorerShortcutHelper.csproj
 - xbuild /p:TargetFrameworkProfile= ./src/LessMsi/LessMsi.csproj
