# Since Ubuntu uses very old versions of mono for stability (http://mono-project.com/DistroPackages/Ubuntu) and there isn't a trivial way to update them that I know of, I'm switching to objective-c to get a mac box which we can easily install recent versions of mono on.
# language: c
# 
# install:
#  - sudo apt-get install mono-devel mono-gmcs nunit-console
# 
install:
 - sudo apt-add-repository -y 'deb http://debian.meebey.net/experimental/mono/'
 - sudo apt-get install mono # mono should include everything needed.

script:
 - xbuild /p:TargetFrameworkProfile= ./src/ExplorerShortcutHelper/ExplorerShortcutHelper.csproj
 - xbuild /p:TargetFrameworkProfile= ./src/LessMsi/LessMsi.csproj
